config/routes.rb
Rails.application.routes.draw do
  get 'links/redirect/:short_code', to: 'links#redirect', as: :links_redirect
  # constraints(domain: 'bit.sh') do
  #   get '/:short_code', to: 'urls#redirect', as: :bit_redirect
  # end
  
  get '/:short_code', to: 'urls#redirect'
  # Define the route for redirecting from url.softalx.com to shorturl.softalx.com
  constraints(host: 'url.softalx.com') do
    get '/', to: redirect('https://shorturl.softalx.com')  # Redirect root path

    get '/:short_code', to: 'urls#redirect'  # Handle shortened URLs
  end
  
  namespace :account do
    resource :subscription, only: [ :update]
    get 'dashboard', to: 'dashboard#home'
    get 'dashboard/subscription', to: 'dashboard#subscription'
    post 'revert_masquerade', to: "dashboard#revert_masquerade"
    # setting
    get 'settings/change_password', to: 'setting#change_password'
    get 'settings/profile', to: 'setting#profile'

    resources :urls, param: :short_code
  end


  namespace :admin do
    resources :payment_methods, only: [:create, :destroy]

    resources :currency_pairs, only: [:create, :destroy] do
      collection do
        post :import_csv
      end
    end

    resource :site, only: [:new, :create, :edit, :update]
    get 'dashboard', to: 'dashboard#home'
    get 'users', to: 'dashboard#users'
    get 'users/:id', to: 'dashboard#show'
    post 'masquerade_as_account', to: 'dashboard#masquerade_as_account'
    # delete account
    delete 'users/:id', to: 'dashboard#destroy'
    # mails
    get 'emails', to: 'email#sent'
    get 'email/new', to: 'email#new'
    post 'emails', to: 'email#create'
        # settings
    get 'settings/account', to: 'setting#account'
    get 'settings/password', to: 'setting#admin_password'
    get 'settings/site_details', to: 'setting#site_details'
    get 'settings/currency_pairs', to: 'setting#currency_pairs'
    get 'settings/payment_method', to: 'setting#payment_methods'

  end

  devise_for :accounts, controllers: {
    sessions: 'accounts/sessions',
    registrations: 'accounts/registrations',
    passwords: 'accounts/passwords',
    confirmations: 'accounts/confirmations'
    }, path: 'auth', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    registration: 'account',
    sign_up: 'sign_up'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    }, path: 'admin', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: 'user',
    sign_up: 'sign_up'
  }

  root 'pages#home'

  post '/fetch_title', to: 'title_fetcher#fetch_title'
end

app/controllers/account/dashboard_controller.rb
class Account::DashboardController < AccountController
  def home
    @title = "Account Dashboard"
    @clicks_count = current_account.urls.map(&:click_count).sum
  end

  def subscription
    @title = "Account Subscription"
    @subscription = current_account.subscription || @current_account.build_subscription(plan: 'free') # Create a subscription if not present
  end

  def revert_masquerade
    # Ensure the current user is an admin and is masquerading as another user
    if current_account && user_masquerade?
      # Clear the masquerade_user_id from the session
      session.delete(:masquerade_user_id)
      # session.delete(:account_id)
      sign_out(current_account)

      redirect_to admin_dashboard_path, notice: "You have reverted back to your admin account."
    else
      # Handle unauthorized access or non-masquerade mode
      redirect_to admin_dashboard_path, alert: "You are not currently masquerading as another user."
    end
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController
  def home
    @title = "Home"
    @total_acc = Account.count
    @total_trades = Trade.count
    @total_deposit = Deposit.count
    @total_withdrawal = Withdrawal.count
    @recent_deposits = Deposit.includes(:account, :payment_method).order(id: :desc).limit(5)
    @recent_withdrawals = Withdrawal.includes(:payment_method, :account).order(id: :desc).limit(5)
    @recent_trades = Trade.includes(:currency_pair, :account).order(id: :desc).limit(5)
  end

  def users
    @title = "Users"
    @q = Account.ransack(params[:q])
    @pagy, @accounts = pagy(@q.result(distinct: true).includes(avatar_attachment: :blob).order(id: :desc), items: 8)
    # @pagy, @accounts = pagy(Account.includes(avatar_attachment: :blob).order(id: :desc), items: 8)
  end

  def masquerade_as_account
    account = Account.find(params[:id])

    # Store the current user's ID in the session
    session[:masquerade_user_id] = current_user.id

    sign_in(account)
    
    redirect_to account_dashboard_path
    flash[:notice] = "Masquerading as #{account.email}"
  end

  def show
    @account = Account.find(params[:id])
    @title = "#{@account.first_name.presence || @account.username}'s profile"
  end

  def destroy
    @account = Account.find(params[:id])
    if @account.present?
      @account.destroy
      redirect_to admin_users_path, notice: "Account Deleted successfully!"
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/admin/dashboard/show.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
	<h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Users /</span> Profile</h4>
	<div class="row">
		<div class="col-md-12">
			<div class="card mb-4">
				<h5 class="card-header">Profile Details</h5>
				<div class="card-body">
					<div class="d-flex align-items-start align-items-sm-center gap-4" data-controller="previews">
						<% if @account.avatar.present? %>
							<%= image_tag(@account.avatar.variant(resize_to_fill: [200, 200]),  class: "d-block rounded", height: 200, width: 200, id: "uploadAvatar", alt: "account-avatar") %>
						<% else %>
							<%= image_tag "img/avatars/1.png", alt: "account-avatar", class: "d-block rounded", height: 200, width: 200  %>
						<% end %>
					</div>
				</div>
				<hr class="my-0">
				<div class="card-body">
					<div class="row">
						<div class="mb-3 col-md-6">
							<strong>First Name:</strong> <%= @account.first_name.present? ? @account.first_name : "NIL" %>
						</div>
						<div class="mb-3 col-md-6">
							<strong>Last Name:</strong> <%= @account.last_name.present? ? @account.last_name : "NIL" %>
						</div>
						<div class="mb-3 col-md-6">
							<strong>Email:</strong> <%= @account.email.present? ? @account.email : "NIL" %>
						</div>
						<div class="mb-3 col-md-6">
							<strong>Username:</strong> <%= @account.username.present? ? @account.username : "NIL" %>
						</div>
						<div class="mb-3 col-md-6">
							<strong>Phone Number:</strong> <%= @account.phone_number.present? ? @account.phone_number : "NIL" %>
						</div>
						<div class="mb-3 col-md-6">
							<strong>Address:</strong> <%= @account.address.present? ? @account.address : "NIL" %>
						</div>
						<div class="mb-3 col-md-6">
							<strong>State:</strong> <%= @account.state.present? ? @account.state : "NIL" %>
						</div>
						<div class="mb-3 col-md-6">
							<strong>Zip Code:</strong> <%= @account.zip_code.present? ? @account.zip_code : "NIL" %>
						</div>
						<div class="mb-3 col-md-6">
							<strong>Country:</strong> <%= @account.country.present? ? @account.country : "NIL" %>
						</div>
						<div class="mb-3 col-md-6">
							<strong>Date of Birth:</strong> <%= @account.date_of_birth.present? ? @account.date_of_birth : "NIL" %>
						</div>
						<div class="mb-3 col-md-6">
							<strong>Gender:</strong> <%= @account.gender.present? ? @account.gender : "NIL" %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/admin/dashboard/users.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
	<h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Admin /</span> Users</h4>
	<div class="row">
		<div class="card">
			<div class="col-md-3">
				<%= search_form_for @q, url: admin_users_url do |f| %>
					<div class="input-group mt-3 mb-2">
						<%= f.search_field :email_or_first_name_or_last_name_cont, class: "form-control", placeholder: "Search user..." %>
						<%# <input type="text" class="form-control" placeholder="Search User..." aria-label="Search User..." aria-describedby="button-addon2"> %>
						<button class="btn btn-primary" type="submit" id="button-addon2" data-turbo="false">
							<span class="tf-icons bx bx-search-alt"></span>
							Search
						</button>
					</div>
				<% end %>
			</div>
			<div class="table-responsive text-nowrap">
				<table class="table table-striped mb-2">
					<thead>
						<tr>
							<th>Email</th>
							<th>Username</th>
							<th>Names</th>
							<th>Image</th>
							<th>Status</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody class="table-border-bottom-0">
						<% @accounts.each do |account|  %>
							<tr>
								<td><%= account.email %></td>
								<td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong><%= account.username %></strong></td>
								<% full_name = "#{account.first_name} #{account.last_name}" if account.first_name.present? && account.last_name.present? %>
								<td><%= full_name.present? ? full_name : 'awaiting names' %></td>
								<td>
									<ul class="list-unstyled users-list m-0 avatar-group d-flex align-items-center">
										<li data-bs-toggle="tooltip" data-popup="tooltip-custom" data-bs-placement="top" class="avatar avatar-xs pull-up" title="" data-bs-original-title="<%= full_name.present? ? full_name : 'awaiting names' %>">
											<%= account.avatar.present? ? image_tag(account.avatar.variant(resize_to_fill: [100, 100]), class: "rounded-circle", alt: "Avatar") : image_tag("img/avatars/5.png", alt: "avatar", class: "rounded-circle") %>
										</li>
									</ul>
								</td>
								<td><span class="badge bg-label-primary me-1">Active</span></td>
								<td>
									<div class="dropdown" >
										<button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
											<i class="bx bx-dots-vertical-rounded"></i>
										</button>
										<div class="dropdown-menu" >
											<a class="dropdown-item text-info" href="<%= admin_url(account) %>" data-turbo="false"><i class="bx bx-show-alt me-1"></i> view</a>
											<%# <a class="dropdown-item" href="javascript:void(0);"><i class="bx bx-edit-alt me-1"></i> Edit</a> %>
											<a class="dropdown-item" href="<%= admin_masquerade_as_account_path(id: account.id) %>" data-turbo-method="post"><i class="bx bx-log-in me-1"></i> Login as</a>
											<a class="dropdown-item text-danger" href="<%= admin_url(account) %>" data-turbo-method="delete" data-turbo-confirm="Are you sure? all the records of <%= "#{full_name}" %> will be deleted "><i class="bx bx-trash me-1"></i> Delete</a>
										</div>
									</div>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
		<%# pagination %>
		<%= render 'admin/shared/pagy', locals: {pagy: @pagy} %>
	</div>
</div>