config/routes.rb
Rails.application.routes.draw do
  get 'links/redirect/:short_code', to: 'links#redirect', as: :links_redirect
  # constraints(domain: 'bit.sh') do
  #   get '/:short_code', to: 'urls#redirect', as: :bit_redirect
  # end
  
  get '/:short_code', to: 'urls#redirect'
  # Define the route for redirecting from url.softalx.com to shorturl.softalx.com
  constraints(host: 'url.softalx.com') do
    get '/', to: redirect('https://shorturl.softalx.com')  # Redirect root path

    get '/:short_code', to: 'urls#redirect'  # Handle shortened URLs
  end
  
  namespace :account do
    resource :subscription, only: [ :update]
    get 'dashboard', to: 'dashboard#home'
    get 'dashboard/subscription', to: 'dashboard#subscription'
    post 'revert_masquerade', to: "dashboard#revert_masquerade"
    # setting
    get 'settings/change_password', to: 'setting#change_password'
    get 'settings/profile', to: 'setting#profile'

    resources :urls, param: :short_code
  end


  namespace :admin do
    resources :payment_methods, only: [:create, :destroy]

    resources :currency_pairs, only: [:create, :destroy] do
      collection do
        post :import_csv
      end
    end

    resource :site, only: [:new, :create, :edit, :update]
    get 'dashboard', to: 'dashboard#home'
    get 'users', to: 'dashboard#users'
    get 'users/:id', to: 'dashboard#show'
    post 'masquerade_as_account', to: 'dashboard#masquerade_as_account'
    # delete account
    delete 'users/:id', to: 'dashboard#destroy'
    # mails
    get 'emails', to: 'email#sent'
    get 'email/new', to: 'email#new'
    post 'emails', to: 'email#create'
        # settings
    get 'settings/account', to: 'setting#account'
    get 'settings/password', to: 'setting#admin_password'
    get 'settings/site_details', to: 'setting#site_details'
    get 'settings/currency_pairs', to: 'setting#currency_pairs'
    get 'settings/payment_method', to: 'setting#payment_methods'

  end

  devise_for :accounts, controllers: {
    sessions: 'accounts/sessions',
    registrations: 'accounts/registrations',
    passwords: 'accounts/passwords',
    confirmations: 'accounts/confirmations'
    }, path: 'auth', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    registration: 'account',
    sign_up: 'sign_up'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    }, path: 'admin', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: 'user',
    sign_up: 'sign_up'
  }

  root 'pages#home'

  post '/fetch_title', to: 'title_fetcher#fetch_title'
end

app/controllers/account/setting_controller.rb
class Account::SettingController < AccountController
  before_action :check_profile_completion, only: [:profile]

  def change_password
    @title = "Change Your Password"
    @resource = current_account
    @resource_name = :account
    @error_messages = flash[:alert] if flash[:alert].present?
  end

  def profile
    @resource_name = :account
    name = current_account.first_name.present? ? current_account.first_name : current_account.username
    @title = "#{name}'s Profile"
  end

  private

  def check_profile_completion
    if current_account && (current_account.first_name.blank? || current_account.last_name.blank? || current_account.address.blank? || current_account.state.blank? || current_account.country.blank?)
      redirect_to edit_account_registration_path, alert: "Please complete your profile information."
    end
  end

end

app/controllers/admin/setting_controller.rb
class Admin::SettingController < AdminController
  def account
    @title = "Account Details"
    @resource = current_user
    @resource_name = :user
  end

  def admin_password
    @title = "Account Password"
    @resource = current_user
    @resource_name = :user
  end

  def site_details
    @title = "Site Contact Details"

     @site = Site.first_or_initialize
  end

  def currency_pairs
    @title = "Currency Pairs"
    @currency_pair = CurrencyPair.new

    @pagy, @currency_pairs = pagy(CurrencyPair.all, items: 5)
  end

  def payment_methods
    @title = "Payment Method" 

    @payment_method = PaymentMethod.new
    @payment_methods = PaymentMethod.all
  end

end

app/views/admin/setting/account.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
	<h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Settings /</span> Account</h4>
	<div class="row">
		<div class="col-md-12">
			<div class="card mb-4">
				<h5 class="card-header">Profile Details</h5>
				<!-- Account -->
				<%= form_for(@resource, as: @resource_name, url: registration_path(@resource_name), html: { method: :put }, data: {turbo: false}) do |f| %>
					<div class="card-body">
						<div class="d-flex align-items-start align-items-sm-center gap-4" data-controller="previews">
							<% if current_user.avatar.present? %>
								<%= image_tag(current_user.avatar.variant(resize_to_fill: [100, 100]), data: {previews_target: "preview"}, class: "d-block rounded", height: 100, width: 100, id: "uploadAvatar", alt: "account-avatar") %>
							<% else %>
								<%=  image_tag "img/avatars/1.png", data: {previews_target: "preview"}, alt: "account-avatar", class: "d-block rounded", height: 100, width: 100, id: "uploadedAvatar" %>
							<% end %>
							<div class="button-wrapper">
								<label for="upload" class="btn btn-primary me-2 mb-4" tabindex="0">
									<span class="d-none d-sm-block">Upload new photo</span>
									<i class="bx bx-upload d-block d-sm-none"></i>
									<%= f.file_field :avatar, id: "upload", style: "display: none", data: { previews_target: "input", action: "change->previews#preview" } %>
								</label>
								<p class="text-muted mb-0">Allowed JPG or PNG. Max size of 800K</p>
							</div>
						</div>
					</div>
					<hr class="my-0">
					<div class="card-body">
						<div class="row">
							<div class="mb-3 col-md-6">
								<label for="firstName" class="form-label">First Name</label>
								<%= f.text_field :first_name, class: "form-control", placeholder: "John" %>
							</div>
							<div class="mb-3 col-md-6">
								<label for="lastName" class="form-label">Last Name</label>
								<%= f.text_field :last_name, class: "form-control", placeholder: "Doe" %>
							</div>
							<div class="mb-3 col-md-6">
								<label for="email" class="form-label">E-mail</label>
								<%= f.email_field :email, autocomplete: "email", class: "form-control", readonly: true %>
							</div>
							<div class="mb-3 col-md-6">
								<label for="organization" class="form-label">Username</label> <span class="text-danger">*</span>
								<%= f.text_field :username, class: "form-control" %>
							</div>
						</div>
						<div class="mt-2">
							<button type="submit" class="btn btn-primary me-2">Save changes</button>
						</div>
					</div>
				<% end %>
				<!-- /Account -->
			</div>
		</div>
	</div>
</div>

app/views/admin/setting/admin_password.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
	<h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Settings /</span> Security</h4>
	<div class="row">
		<div class="col-md-6">
			<div class="card mb-4">
				<h5 class="card-header">Change Password</h5>
				<div class="card-body">
					<%= form_for(@resource, as: @resource_name, url: registration_path(@resource_name), html: { method: :put }, data: {turbo: false}) do |f| %>
						<%= render "users/shared/error_messages", resource: @resource %>
						<h3>Password should be minimum of 6 characters</h3>
						<div class="mb-3">
							<%= f.label :current_password, class: "form-label" %>
							<%= f.password_field :current_password, class: "form-control" %>
						</div>
						<div class="mb-3">
							<%= f.label :password, class: "form-label" %>
							<%= f.password_field :password, class: "form-control" %>
						</div>
						<div class="mb-3">
							<%= f.label :password_confirmation, class: "form-label" %>
							<%= f.password_field :password_confirmation, class: "form-control" %>
						</div>
						<div class="actions">
							<%= f.submit "Change Password", class: 'btn btn-primary me-2' %>
						</div>
					<% end %>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="card mb-4">
				<div class="card-body">
					<div class="text-center">
						<%= image_tag "https://cdn-icons-png.flaticon.com/512/6195/6195699.png", class: "image-fluid", width: "60%" %>
					</div>
				</div>
			</div>
		</div>
		<!-- Form controls -->
	</div>
</div>

app/views/admin/setting/currency_pairs.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
	<h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Settings /</span> Currency Pairs</h4>
	<div class="row">
		<div class="col-md-6 mx-auto">
			<div class="card mb-4">
				<h5 class="card-header">Create Currency Pair</h5>
				<!-- Account -->
				<div class="card-body">
					<%= form_with(model: [:admin, @currency_pair], url: admin_currency_pairs_path, local: true) do |form| %>
						<% if @currency_pair.errors.any? %>
							<div id="error_explanation">
								<h2><%= pluralize(@currency_pair.errors.count, "error") %> prohibited this currency pair from being saved:</h2>
								<ul>
									<% @currency_pair.errors.full_messages.each do |message| %>
										<li><%= message %></li>
									<% end %>
								</ul>
							</div>
						<% end %>
						<div class="row">
							<div class="mb-3 col-md-6">
								<label class="form-label" for="phoneNumber">Base Currency</label>
								<div class="input-group input-group-merge">
									<%= form.text_field :base_currency, class: "form-control", placeholder: "USD", required: true %>
								</div>
							</div>
							<div class="mb-3 col-md-6">
								<label class="form-label" for="phoneNumber">Quote Currency</label>
								<div class="input-group input-group-merge">
									<%= form.text_field :quote_currency, class: "form-control", placeholder: "EUR", required: true %>
								</div>
							</div>
						</div>
						<div class="mt-2">
							<%= form.submit 'Create Pair', class: "btn btn-primary me-2", data: {turbo: false} %>
						</div>
					<% end %>
				</div>
			</div>
		</div>
		<!-- Basic Layout -->
		<div class="col-xxl">
			<div class="card mb-4">
				<div class="card-header d-flex align-items-center justify-content-between">
					<h5 class="mb-0">Import CSV</h5>
				</div>
				<div class="card-body">
					<%= form_with(url: import_csv_admin_currency_pairs_path, multipart: true) do |form| %>
						<div class="row">
							<div class="mb-3 col-md-12">
								<label class="form-label" for="phoneNumber">Upload CSV file</label>
								<div class="input-group input-group-merge">
									<%= form.file_field :file, class: "form-control", required: true %>
								</div>
							</div>
						</div>
						<div class="mt-2">
							<button type="submit"  class="btn btn-primary me-2" data-turbo="false">Import CSV</button>
						</div>
					<% end %>
				</div>
			</div>
			<!-- Basic with Icons -->
		</div>
	</div>
	<% if @currency_pairs.present? %>
		<div class="card">
			<div class="table-responsive text-nowrap">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Currency Pairs</th>
							<th>Status</th>
							<th>Created Date</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody class="table-border-bottom-0">
						<% @currency_pairs.each do |curr| %>
							<tr>
								<td><strong><%= curr.base_currency %> / <%= curr.quote_currency %></strong></td>
								<td><span class="badge bg-label-primary me-1">Active</span></td>
								<td><%= curr.created_at.strftime("%m/%d/%y - %l:%M%P") %></td>
								<td>
									<%= link_to 'Delete', admin_currency_pair_path(curr), class: "btn btn-sm btn-outline-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	<% else %>
		<div class="card mb-4 ">
			<div class="card-body mx-auto">
				<p class="card-text">
					You have no Currency pair 
				</p>
			</div>
		</div>
	<% end %>
	<%# pagination %>
	<%= render 'admin/shared/pagy', locals: {pagy: @pagy} %>
</div>

app/views/admin/setting/payment_methods.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
	<h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Settings /</span> Payment Method</h4>
	<div class="row">
		<div class="col-md-8 mx-auto">
			<div class="card mb-4">
				<h5 class="card-header">Create Payment Method</h5>
				<!-- Account -->
				<div class="card-body">
					<%= form_with(model: [:admin, @payment_method], url: admin_payment_methods_path, local: true) do |form| %>
						<% if @payment_method.errors.any? %>
							<div id="error_explanation">
								<h2><%= pluralize(@payment_method.errors.count, "error") %> prohibited this currency pair from being saved:</h2>
								<ul>
									<% @payment_method.errors.full_messages.each do |message| %>
										<li><%= message %></li>
									<% end %>
								</ul>
							</div>
						<% end %>
						<div class="row">
							<div class="mb-3 col-md-4">
								<label class="form-label" for="phoneNumber">Payment Name</label>
								<div class="input-group input-group-merge">
									<%= form.text_field :name, class: "form-control", placeholder: "eg Bitcoin", required: true %>
								</div>
							</div>
							<div class="mb-3 col-md-4">
								<label class="form-label" for="phoneNumber">Wallet Address</label>
								<div class="input-group input-group-merge">
									<%= form.text_field :wallet, class: "form-control", placeholder: "y48fhxxxxxxxxxxxxxxxxxxx", required: true %>
								</div>
							</div>
							<div class="mb-3 col-md-4">
								<label class="form-label" for="phoneNumber">Wallet Qrcode</label>
								<div class="input-group input-group-merge">
									<%= form.file_field :wallet_qrcode, class: "form-control", placeholder: "", required: true %>
								</div>
							</div>
						</div>
						<div class="mt-2">
							<%= form.submit 'Create ', class: "btn btn-primary me-2", data: {turbo: false} %>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<% if @payment_methods.present? %>
		<div class="card">
			<div class="table-responsive text-nowrap">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Currency Pairs</th>
							<th>Address</th>
							<th>Qrcode</th>
							<th>Created Date</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody class="table-border-bottom-0">
						<% @payment_methods.each do |pay| %>
							<tr>
								<td><strong><%= pay.name %> </strong></td>
								<td><%= pay.wallet %></td>
								<td><%= pay.wallet_qrcode.present? ? image_tag(pay.wallet_qrcode, width: 50) : "No Qrcode" %></td>
								<td><%= pay.created_at.strftime("%m/%d/%y - %l:%M%P") %></td>
								<td>
									<%= link_to 'Delete', admin_payment_method_path(pay), class: "btn btn-sm btn-outline-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	<% else %>
		<div class="card mb-4 ">
			<div class="card-body mx-auto">
				<p class="card-text">
					You have no Payment method yet.
				</p>
			</div>
		</div>
	<% end %>
</div>

app/views/admin/setting/site_details.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
	<h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Settings /</span> Contact Details</h4>
	<div class="row">
		<div class="col-md-6">
			<div class="card mb-4">
				<h5 class="card-header">Form</h5>
				<!-- Account -->
				<hr class="my-0">
				<div class="card-body">
					<% if @site.errors.any? %>
						<div id="error_explanation">
							<h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>
							<ul>
								<% @site.errors.full_messages.each do |msg| %>
									<li><%= msg %></li>
								<% end %>
							</ul>
						</div>
					<% end %>
					<%= form_with(model: [:admin, @site], url: @site.persisted? ? admin_site_path(@site) : admin_site_path, method: @site.persisted? ? :patch : :post, data: {turbo: false}) do |form| %>
						<%#= form.hidden_field :id %>
						<div class="row">
							<div class="mb-3 col-md-12">
								<label for="email" class="form-label">Support E-mail</label>
								<%= form.email_field :contact_email, class: "form-control", placeholder: "john.doe@example.com" %>
							</div>
							<div class="mb-3 col-md-12">
								<label class="form-label" for="phoneNumber">Support Phone Number</label>
								<div class="input-group input-group-merge">
									<%= form.text_field :contact_number, class: "form-control", placeholder: "(+xx) 202 555 0111" %>
								</div>
							</div>
							<div class="mb-3 col-md-12">
								<label for="address" class="form-label">Address</label>
								<%= form.text_area :contact_address, class: "form-control", rows: 4, placeholder: "123 Main str" %>
							</div>
						</div>
						<div class="mt-2">
							<%= form.submit 'Save changes', class: "btn btn-primary me-2" %>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>