config/routes.rb
Rails.application.routes.draw do
  get 'links/redirect/:short_code', to: 'links#redirect', as: :links_redirect
  # constraints(domain: 'bit.sh') do
  #   get '/:short_code', to: 'urls#redirect', as: :bit_redirect
  # end
  
  get '/:short_code', to: 'urls#redirect'
  # Define the route for redirecting from url.softalx.com to shorturl.softalx.com
  constraints(host: 'url.softalx.com') do
    get '/', to: redirect('https://shorturl.softalx.com')  # Redirect root path

    get '/:short_code', to: 'urls#redirect'  # Handle shortened URLs
  end
  
  namespace :account do
    resource :subscription, only: [ :update]
    get 'dashboard', to: 'dashboard#home'
    get 'dashboard/subscription', to: 'dashboard#subscription'
    post 'revert_masquerade', to: "dashboard#revert_masquerade"
    # setting
    get 'settings/change_password', to: 'setting#change_password'
    get 'settings/profile', to: 'setting#profile'

    resources :urls, param: :short_code
  end


  namespace :admin do
    resources :payment_methods, only: [:create, :destroy]

    resources :currency_pairs, only: [:create, :destroy] do
      collection do
        post :import_csv
      end
    end

    resource :site, only: [:new, :create, :edit, :update]
    get 'dashboard', to: 'dashboard#home'
    get 'users', to: 'dashboard#users'
    get 'users/:id', to: 'dashboard#show'
    post 'masquerade_as_account', to: 'dashboard#masquerade_as_account'
    # delete account
    delete 'users/:id', to: 'dashboard#destroy'
    # mails
    get 'emails', to: 'email#sent'
    get 'email/new', to: 'email#new'
    post 'emails', to: 'email#create'
        # settings
    get 'settings/account', to: 'setting#account'
    get 'settings/password', to: 'setting#admin_password'
    get 'settings/site_details', to: 'setting#site_details'
    get 'settings/currency_pairs', to: 'setting#currency_pairs'
    get 'settings/payment_method', to: 'setting#payment_methods'

  end

  devise_for :accounts, controllers: {
    sessions: 'accounts/sessions',
    registrations: 'accounts/registrations',
    passwords: 'accounts/passwords',
    confirmations: 'accounts/confirmations'
    }, path: 'auth', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    registration: 'account',
    sign_up: 'sign_up'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    }, path: 'admin', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: 'user',
    sign_up: 'sign_up'
  }

  root 'pages#home'

  post '/fetch_title', to: 'title_fetcher#fetch_title'
end

app/views/admin/shared/_pagy.html.erb
<% if @pagy.pages > 1 %>
	<div class="card mt-4 table-responsive">
		<!-- Basic Pagination -->
		<div class="card-body mx-auto py-1 ">
			<div class="row ">
				<div class="col ">
					<div class="demo-inline-spacing mb-3">
						<%== pagy_nav(@pagy)  %>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/admin/shared/_sidebar.html.erb
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
	<div class="app-brand demo">
		<a href="<%= admin_dashboard_path %>" class="app-brand-link" data-turbo="false">
			<span class="app-brand-logo demo">
				<svg
                  width="25"
                  viewBox="0 0 25 42"
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  xmlns:xlink="http://www.w3.org/1999/xlink"
                >
					<defs>
						<path
                      d="M13.7918663,0.358365126 L3.39788168,7.44174259 C0.566865006,9.69408886 -0.379795268,12.4788597 0.557900856,15.7960551 C0.68998853,16.2305145 1.09562888,17.7872135 3.12357076,19.2293357 C3.8146334,19.7207684 5.32369333,20.3834223 7.65075054,21.2172976 L7.59773219,21.2525164 L2.63468769,24.5493413 C0.445452254,26.3002124 0.0884951797,28.5083815 1.56381646,31.1738486 C2.83770406,32.8170431 5.20850219,33.2640127 7.09180128,32.5391577 C8.347334,32.0559211 11.4559176,30.0011079 16.4175519,26.3747182 C18.0338572,24.4997857 18.6973423,22.4544883 18.4080071,20.2388261 C17.963753,17.5346866 16.1776345,15.5799961 13.0496516,14.3747546 L10.9194936,13.4715819 L18.6192054,7.984237 L13.7918663,0.358365126 Z"
                      id="path-1"
                    ></path>
						<path
                      d="M5.47320593,6.00457225 C4.05321814,8.216144 4.36334763,10.0722806 6.40359441,11.5729822 C8.61520715,12.571656 10.0999176,13.2171421 10.8577257,13.5094407 L15.5088241,14.433041 L18.6192054,7.984237 C15.5364148,3.11535317 13.9273018,0.573395879 13.7918663,0.358365126 C13.5790555,0.511491653 10.8061687,2.3935607 5.47320593,6.00457225 Z"
                      id="path-3"
                    ></path>
						<path
                      d="M7.50063644,21.2294429 L12.3234468,23.3159332 C14.1688022,24.7579751 14.397098,26.4880487 13.008334,28.506154 C11.6195701,30.5242593 10.3099883,31.790241 9.07958868,32.3040991 C5.78142938,33.4346997 4.13234973,34 4.13234973,34 C4.13234973,34 2.75489982,33.0538207 2.37032616e-14,31.1614621 C-0.55822714,27.8186216 -0.55822714,26.0572515 -4.05231404e-15,25.8773518 C0.83734071,25.6075023 2.77988457,22.8248993 3.3049379,22.52991 C3.65497346,22.3332504 5.05353963,21.8997614 7.50063644,21.2294429 Z"
                      id="path-4"
                    ></path>
						<path
                      d="M20.6,7.13333333 L25.6,13.8 C26.2627417,14.6836556 26.0836556,15.9372583 25.2,16.6 C24.8538077,16.8596443 24.4327404,17 24,17 L14,17 C12.8954305,17 12,16.1045695 12,15 C12,14.5672596 12.1403557,14.1461923 12.4,13.8 L17.4,7.13333333 C18.0627417,6.24967773 19.3163444,6.07059163 20.2,6.73333333 C20.3516113,6.84704183 20.4862915,6.981722 20.6,7.13333333 Z"
                      id="path-5"
                    ></path>
					</defs>
					<g id="g-app-brand" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
						<g id="Brand-Logo" transform="translate(-27.000000, -15.000000)">
							<g id="Icon" transform="translate(27.000000, 15.000000)">
								<g id="Mask" transform="translate(0.000000, 8.000000)">
									<mask id="mask-2" fill="white">
										<use xlink:href="#path-1"></use>
									</mask>
									<use fill="#696cff" xlink:href="#path-1"></use>
									<g id="Path-3" mask="url(#mask-2)">
										<use fill="#696cff" xlink:href="#path-3"></use>
										<use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-3"></use>
									</g>
									<g id="Path-4" mask="url(#mask-2)">
										<use fill="#696cff" xlink:href="#path-4"></use>
										<use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-4"></use>
									</g>
								</g>
								<g
                          id="Triangle"
                          transform="translate(19.000000, 11.000000) rotate(-300.000000) translate(-19.000000, -11.000000) "
                        >
									<use fill="#696cff" xlink:href="#path-5"></use>
									<use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-5"></use>
								</g>
							</g>
						</g>
					</g>
				</svg>
			</span>
			<span class="app-brand-text demo menu-text fw-bolder ms-2">Sneat</span>
		</a>
		<a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
			<i class="bx bx-chevron-left bx-sm align-middle"></i>
		</a>
	</div>
	<div class="menu-inner-shadow"></div>
	<ul class="menu-inner py-1">
		<!-- Dashboard -->
		<li class="menu-item <%= 'active' if request.path == admin_dashboard_path %>">
			<a href="<%= admin_dashboard_path %>" class="menu-link" data-turbo="false">
				<i class="menu-icon tf-icons bx bx-home-circle"></i>
				<div data-i18n="Analytics">Dashboard</div>
			</a>
		</li>
		<li class="menu-header small">
			<span class="menu-header-text">Pages</span>
		</li>
		<% if defined?(@account) && @account.present? %>
			<li class="menu-item <%= 'active open' if request.path == admin_users_path || request.path == admin_path(@account) %>">
			<% else %>
				<li class="menu-item <%= 'active open' if request.path == admin_users_path %>">
				<% end %>
				<a href="javascript:void(0);" class="menu-link menu-toggle">
					<i class="menu-icon tf-icons bx bx-user"></i>
					<div data-i18n="Account Settings">Users</div>
				</a>
				<ul class="menu-sub">
					<li class="menu-item <%= 'active' if request.path == admin_users_path %>">
						<a href="<%= admin_users_path%>" class="menu-link" data-turbo="false">
							<div data-i18n="Account">Overview</div>
						</a>
					</li>
				</ul>
			</li>
			<!-- Extended components -->
			<li class="menu-item <%= 'active open' if request.path == admin_trade_active_path || request.path === admin_trade_inactive_path %>">
				<a href="javascript:void(0)" class="menu-link menu-toggle">
					<i class="menu-icon tf-icons bx bx-candles"></i>
					<div data-i18n="Extended UI">Trades</div>
				</a>
				<ul class="menu-sub">
					<li class="menu-item <%= 'active' if request.path == admin_trade_active_path %>">
						<a href="<%= admin_trade_active_path %>" class="menu-link" data-turbo="false">
							<div data-i18n="Perfect Scrollbar">Active</div>
						</a>
					</li>
					<li class="menu-item <%= 'active' if request.path == admin_trade_inactive_path %>">
						<a href="<%= admin_trade_inactive_path %>" class="menu-link" data-turbo="false">
							<div data-i18n="Text Divider">Inactive</div>
						</a>
					</li>
				</ul>
			</li>
			<!-- Extended components -->
			<% if defined?(@deposit) && @deposit.present? %>
				<li class="menu-item <%= 'active open' if request.path == admin_deposit_pending_path || request.path == admin_deposit_approved_path || request.path == admin_deposit_declined_path || request.path == admin_deposit_path(@deposit) %>">
				<% else %>
					<li class="menu-item <%= 'active open' if request.path == admin_deposit_pending_path || request.path == admin_deposit_approved_path || request.path == admin_deposit_declined_path %>">
					<% end %>
					<a href="javascript:void(0)" class="menu-link menu-toggle">
						<i class="menu-icon tf-icons bx bx-wallet"></i>
						<div data-i18n="Extended UI">Deposits</div>
					</a>
					<ul class="menu-sub">
						<li class="menu-item <%= 'active' if request.path == admin_deposit_pending_path %>">
							<a href="<%= admin_deposit_pending_path %>" class="menu-link" data-turbo='false'>
								<div data-i18n="Perfect Scrollbar">Pending</div>
							</a>
						</li>
						<li class="menu-item <%= 'active' if request.path == admin_deposit_approved_path %>">
							<a href="<%= admin_deposit_approved_path %>" class="menu-link" data-turbo='false'>
								<div data-i18n="Text Divider">Approved</div>
							</a>
						</li>
						<li class="menu-item <%= 'active' if request.path == admin_deposit_declined_path %>">
							<a href="<%= admin_deposit_declined_path %>" class="menu-link" data-turbo='false'>
								<div data-i18n="Text Divider">Declined</div>
							</a>
						</li>
					</ul>
				</li>
				<!-- Extended components -->
				<% if defined?(@withdrawal) && @withdrawal.present? %>
					<li class="menu-item <%= 'active open' if request.path == admin_withdrawal_pending_path || request.path == admin_withdrawal_approved_path || request.path == admin_withdrawal_declined_path || request.path == admin_withdrawal_path(@withdrawal) %>">
					<% else %>
						<li class="menu-item <%= 'active open' if request.path == admin_withdrawal_pending_path || request.path == admin_withdrawal_approved_path || request.path == admin_withdrawal_declined_path %>">
						<% end %>
						<a href="javascript:void(0)" class="menu-link menu-toggle">
							<i class="menu-icon tf-icons bx bx-money-withdraw"></i>
							<div data-i18n="Extended UI">Withdrawals</div>
						</a>
						<ul class="menu-sub">
							<li class="menu-item <%= 'active' if request.path == admin_withdrawal_pending_path %>">
								<a href="<%= admin_withdrawal_pending_path %>" class="menu-link" data-turbo='false'>
									<div data-i18n="Perfect Scrollbar">Pending</div>
								</a>
							</li>
							<li class="menu-item <%= 'active' if request.path == admin_withdrawal_approved_path %>">
								<a href="<%= admin_withdrawal_approved_path %>" class="menu-link" data-turbo='false'>
									<div data-i18n="Text Divider">Approved</div>
								</a>
							</li>
							<li class="menu-item <%= 'active' if request.path == admin_withdrawal_declined_path %>">
								<a href="<%= admin_withdrawal_declined_path %>" class="menu-link" data-turbo='false'>
									<div data-i18n="Text Divider">Declined</div>
								</a>
							</li>
						</ul>
					</li>
					<!-- Components -->
					<!-- Cards -->
					<li class="menu-item <%= 'active' if request.path == admin_emails_path || request.path == admin_email_new_path %>">
						<a href="<%= admin_emails_path %>" class="menu-link" data-turbo="false">
							<i class="menu-icon tf-icons bx bx-envelope"></i>
							<div data-i18n="Basic">Emails</div>
						</a>
					</li>
					<!-- User interface -->
					<li class="menu-item <%= 'active open' if request.path == admin_settings_account_path || request.path == admin_settings_site_details_path || request.path == admin_settings_currency_pairs_path || request.path == admin_settings_payment_method_path || request.path == admin_settings_password_path %>">
						<a href="javascript:void(0)" class="menu-link menu-toggle">
							<i class="menu-icon tf-icons bx bx-cog"></i>
							<div data-i18n="User interface">Settings</div>
						</a>
						<ul class="menu-sub">
							<li class="menu-item <%= 'active' if request.path == admin_settings_account_path %>">
								<a href="<%= admin_settings_account_path %>" class="menu-link" data-turbo="false">
									<div data-i18n="Accordion">Account</div>
								</a>
							</li>
							<li class="menu-item <%= 'active' if request.path == admin_settings_password_path %>">
								<a href="<%= admin_settings_password_path %>" class="menu-link" data-turbo="false">
									<div data-i18n="Accordion">Password</div>
								</a>
							</li>
							<li class="menu-item <%= 'active' if request.path == admin_settings_payment_method_path %>">
								<a href="<%= admin_settings_payment_method_path %>" class="menu-link" data-turbo="false">
									<div data-i18n="Alerts">Payment Methods</div>
								</a>
							</li>
							<%# <li class="menu-item">
					<a href="#" class="menu-link">
						<div data-i18n="Badges">Subscription Plans</div>
					</a>
				</li> %>
							<li class="menu-item <%= 'active' if request.path == admin_settings_currency_pairs_path %>">
								<a href="<%= admin_settings_currency_pairs_path %>" class="menu-link" data-turbo="false">
									<div data-i18n="Buttons">Trade Currency Pairs</div>
								</a>
							</li>
							<li class="menu-item <%= 'active' if request.path == admin_settings_site_details_path %>">
								<a href="<%= admin_settings_site_details_path %>" class="menu-link" data-turbo="false">
									<div data-i18n="Carousel">Contact Details</div>
								</a>
							</li>
						</ul>
					</li>
				</ul>
			</aside>

app/views/admin/shared/_topbar.html.erb
<nav
            class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
            id="layout-navbar"
          >
	<div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
		<a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
			<i class="bx bx-menu bx-sm"></i>
		</a>
	</div>
	<div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
		<!-- Search -->
		<div class="navbar-nav align-items-center">
			<div class="nav-item d-flex align-items-center">
				<%# <i class="bx bx-search fs-4 lh-0"></i>
                  <input
                    type="text"
                    class="form-control border-0 shadow-none"
                    placeholder="Search..."
                    aria-label="Search..."
                  /> %>
			</div>
		</div>
		<!-- /Search -->
		<ul class="navbar-nav flex-row align-items-center ms-auto">
			<!-- Place this tag where you want the button to render. -->
			<%# <li class="nav-item lh-1 me-3">
				<a
                    class="github-button"
                    href="https://github.com/themeselection/sneat-html-admin-template-free"
                    data-icon="octicon-star"
                    data-size="large"
                    data-show-count="true"
                    aria-label="Star themeselection/sneat-html-admin-template-free on GitHub"
                    >Star</a
                  >
			</li> %>
			<!-- User -->
			<li class="nav-item navbar-dropdown dropdown-user dropdown">
				<a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
					<div class="avatar avatar-online">
						<%= current_user.avatar.present? ? image_tag(current_user.avatar.variant(resize_to_fill: [40, 40]), alt: "avatar", class: "w-px-40 h-auto rounded-circle") : image_tag("img/avatars/1.png", alt: "avatar", class: "w-px-40 h-auto rounded-circle") %>
					</div>
				</a>
				<ul class="dropdown-menu dropdown-menu-end">
					<li>
						<a class="dropdown-item" href="#">
							<div class="d-flex">
								<div class="flex-shrink-0 me-3">
									<div class="avatar avatar-online">
										<%= current_user.avatar.present? ? image_tag(current_user.avatar.variant(resize_to_fill: [40, 40]), alt: "avatar", class: "w-px-40 h-auto rounded-circle") : image_tag("img/avatars/1.png", alt: "avatar", class: "w-px-40 h-auto rounded-circle") %>
									</div>
								</div>
								<div class="flex-grow-1">
									<span class="fw-semibold d-block"><%= current_user.first_name.present? ? current_user.first_name : current_user.username %></span>
									<small class="text-muted">Admin</small>
								</div>
							</div>
						</a>
					</li>
					<li>
						<div class="dropdown-divider"></div>
					</li>
					<li>
						<a class="dropdown-item" href="<%= admin_settings_account_path %>" data-turbo="false">
							<i class="bx bx-cog me-2"></i>
							<span class="align-middle">Settings</span>
						</a>
					</li>
					<li>
						<div class="dropdown-divider"></div>
					</li>
					<li>
						<a class="dropdown-item text-danger" href="<%= destroy_user_session_path%>" data-turbo-method="delete" data-turbo-confirm="Are you sure">
							<i class="bx bx-power-off me-2"></i>
							<span class="align-middle ">Log Out</span>
						</a>
					</li>
				</ul>
			</li>
			<!--/ User -->
		</ul>
	</div>
</nav>

app/views/admin/shared/dump.html.erb
<h2>Edit <%= resource_name.to_s.humanize %></h2>
<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.email_field :email, autofocus: true, autocomplete: "email" %>
	</div>
	<% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
		<div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
	<% end %>
	<div class="field">
		<%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
		<%= f.password_field :password, autocomplete: "new-password" %>
		<% if @minimum_password_length %>
			<br />
			<em><%= @minimum_password_length %> characters minimum</em>
		<% end %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation, autocomplete: "new-password" %>
	</div>
	<div class="field">
		<%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
		<%= f.password_field :current_password, autocomplete: "current-password" %>
	</div>
	<div class="actions">
		<%= f.submit "Update" %>
	</div>
<% end %>
<h3>Cancel my account</h3>
<div>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete %></div>
<%= link_to "Back", :back %>